name = "stayfloow"
compatibility_date = "2025-02-01"
pages_build_output_dir = ".open-next/assets"

[functions]
directory = "functions"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
